branch-defaults:
  default:
    environment: develop
environment-defaults:
  develop:
    branch: null
    repository: null
global:
  application_name: app-pollsapi
  default_ec2_keyname: null
  default_platform: Python 3.8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
